export const STORE_PRODUCTS = {
  customBubbleColor: 'mute_custom_bubble_color',
  customTextColor: 'mute_custom_text_color',
  customBackground: 'mute_custom_background',
  adFreeMonthly: 'mute_ad_free_monthly',
  point5000: 'mute_points_5000',
  point11000: 'mute_points_11000',
  point28000: 'mute_points_28000',
  point60000: 'mute_points_60000',
  point200000: 'mute_points_200000',
  point390000: 'mute_points_390000',
  // Theme v2 products must be configured as CONSUMABLE in App Store Connect.
  // The permanent entitlement itself is stored against the signed-in Mute account.
  themeWhite: 'mute_theme_white_unlock_v2',
  themeMint: 'mute_theme_mint_unlock_v2',
  themeOcean: 'mute_theme_ocean_unlock_v2',
  themeLavender: 'mute_theme_lavender_unlock_v2',
  themeSunset: 'mute_theme_sunset_unlock_v2',
  themeMono: 'mute_theme_mono_unlock_v2',
  themeDark: 'mute_theme_dark_unlock_v2',
  legacyThemeWhite: 'mute_theme_white',
  legacyThemeMint: 'mute_theme_mint',
  legacyThemeOcean: 'mute_theme_ocean',
  legacyThemeLavender: 'mute_theme_lavender',
  legacyThemeSunset: 'mute_theme_sunset',
  legacyThemeMono: 'mute_theme_mono',
  legacyThemeDark: 'mute_theme_dark',
} as const;
