import { Room } from './types';

export const rooms: Room[] = [
  {
    id: 'green-table',
    name: '초록 테이블',
    description: '퇴근 후 가볍게 일상을 나누는 작은 대화방이에요.',
    tags: ['일상', '직장인', '느슨한모임'],
    memberCount: 38,
    maxMembers: 50,
    region: '서울',
    category: 'general',
    topSpaceCount: 34,
    isPromoted: true,
    emoji: '☘',
    imageColor: '#DDEFE4',
  },
  {
    id: 'weekend-photo',
    name: '주말 한 장',
    description: '주말에 찍은 사진 한 장과 짧은 이야기를 공유해요.',
    tags: ['사진', '주말', '취미'],
    memberCount: 71,
    maxMembers: 80,
    category: 'member',
    topSpaceCount: 21,
    isActive: true,
    emoji: '◉',
    imageColor: '#E7E4F4',
  },
  {
    id: 'suwon-walk',
    name: '수원 저녁 산책',
    description: '경기 남부에서 안전하게 함께 걷는 산책 모임입니다.',
    tags: ['수원', '산책', '경기남부'],
    memberCount: 24,
    maxMembers: 40,
    region: '경기남부',
    category: 'general',
    topSpaceCount: 13,
    isActive: true,
    emoji: '⌁',
    imageColor: '#F4E6DB',
  },
  {
    id: 'late-cinema',
    name: '늦은 영화 이야기',
    description: '스포일러 구역을 지키며 깊게 영화 이야기를 나눠요.',
    tags: ['영화', '리뷰', '성인'],
    memberCount: 76,
    maxMembers: 80,
    category: 'member',
    topSpaceCount: 55,
    isAdult: true,
    isPromoted: true,
    emoji: '▶',
    imageColor: '#DFEAF1',
  },
  {
    id: 'concept-lab',
    name: '세계관 실험실',
    description: '새로운 설정과 캐릭터 관계를 함께 설계하는 콘셉트 대화방입니다.',
    tags: ['콘셉트', '세계관', '창작'],
    memberCount: 31,
    maxMembers: 60,
    category: 'concept',
    topSpaceCount: 47,
    isActive: true,
    emoji: '◇',
    imageColor: '#E8E5EF',
  },
  {
    id: 'midnight-radio',
    name: '자정 라디오',
    description: '하루의 끝을 라디오 콘셉트로 이야기하는 역할 대화방이에요.',
    tags: ['콘셉트', '라디오', '심야'],
    memberCount: 42,
    maxMembers: 80,
    category: 'concept',
    topSpaceCount: 29,
    isPromoted: true,
    emoji: '◌',
    imageColor: '#E1E9EC',
  },
];

export const stories = [
  {
    id: 's1',
    category: '공지',
    title: '6월 오프라인 산책 투표',
    body: '이번 달 산책 장소 후보를 모았어요. 가능한 날짜와 장소에 투표해 주세요.',
    author: '초록윤',
    comments: 12,
    time: '2시간 전',
  },
  {
    id: 's2',
    category: '일상',
    title: '오늘의 초록 한 장',
    body: '점심시간에 발견한 작은 정원입니다. 다들 오늘 발견한 초록이 있나요?',
    author: '해질녘',
    comments: 7,
    time: '5시간 전',
  },
];
