import type { Room } from "./types";

// This dataset is only enabled by EXPO_PUBLIC_SCREENSHOT_DEMO=1.
// It must never be written to Supabase or mixed with production records.
export const SCREENSHOT_DEMO_ENABLED =
  process.env.EXPO_PUBLIC_SCREENSHOT_DEMO === "1";

const now = Date.now();

export const screenshotDemoRooms: Room[] = [
  {
    id: "green-table",
    name: "오늘의 온도",
    description: "가볍게 안부를 나누고 하루를 기록하는 대화방",
    lastMessage: "사진 분위기가 진짜 좋다",
    tags: [],
    memberCount: 3,
    maxMembers: 40,
    category: "member",
    topSpaceCount: 18,
    isActive: true,
    emoji: "",
    imageColor: "#E8ECEA",
    coverUri: "https://picsum.photos/seed/mute-today/800/800",
    updatedAt: now - 45 * 1000,
    isSample: true,
  },
  {
    id: "demo-room-creative",
    name: "느린 창작소",
    description: "그림과 글, 사진을 천천히 공유해요",
    lastMessage: "새 작업 올렸어요. 피드백 부탁해요!",
    tags: [],
    memberCount: 12,
    maxMembers: 30,
    category: "concept",
    topSpaceCount: 12,
    isActive: true,
    emoji: "",
    imageColor: "#E9E4F2",
    coverUri: "https://picsum.photos/seed/mute-creative/800/800",
    updatedAt: now - 3 * 60 * 1000,
    isSample: true,
  },
  {
    id: "demo-room-weekend",
    name: "주말 사진 기록",
    description: "이번 주에 발견한 장면과 사진을 공유해요",
    lastMessage: "이번 주 사진 주제는 빛으로 할까요?",
    tags: [],
    memberCount: 24,
    maxMembers: 50,
    region: "서울",
    category: "member",
    topSpaceCount: 9,
    isActive: true,
    emoji: "",
    imageColor: "#E6EEF2",
    coverUri: "https://picsum.photos/seed/mute-walk/800/800",
    updatedAt: now - 18 * 60 * 1000,
    isSample: true,
  },
  {
    id: "demo-room-movie",
    name: "밤의 영화관",
    description: "스포일러 구역을 지키며 영화 이야기를 나눠요",
    lastMessage: "이번 주 상영작 투표 열었어요",
    tags: [],
    memberCount: 31,
    maxMembers: 60,
    category: "concept",
    topSpaceCount: 27,
    isPrivate: true,
    emoji: "",
    imageColor: "#E2E5EB",
    coverUri: "https://picsum.photos/seed/mute-cinema/800/800",
    updatedAt: now - 54 * 60 * 1000,
    isSample: true,
  },
  {
    id: "demo-room-coffee",
    name: "커피 한 잔의 기록",
    description: "오늘 마신 커피와 공간을 기록합니다",
    lastMessage: "산미가 은은해서 좋았어요",
    tags: [],
    memberCount: 8,
    maxMembers: 20,
    category: "member",
    topSpaceCount: 5,
    emoji: "",
    imageColor: "#EEE7DF",
    coverUri: "https://picsum.photos/seed/mute-coffee/800/800",
    updatedAt: now - 2 * 60 * 60 * 1000,
    isSample: true,
  },
  {
    id: "demo-room-midnight",
    name: "자정 라디오",
    description: "잠들기 전 짧은 이야기를 남기는 방",
    lastMessage: "오늘도 모두 수고했어요",
    tags: [],
    memberCount: 17,
    maxMembers: 40,
    category: "concept",
    topSpaceCount: 14,
    emoji: "",
    imageColor: "#E3E8ED",
    coverUri: "https://picsum.photos/seed/mute-radio/800/800",
    updatedAt: now - 7 * 60 * 60 * 1000,
    isSample: true,
  },
];

export const screenshotDemoUnreadCounts: Record<string, number> = {
  "green-table": 3,
  "demo-room-creative": 12,
  "demo-room-weekend": 1,
  "demo-room-movie": 0,
  "demo-room-coffee": 7,
  "demo-room-midnight": 0,
};

export const screenshotDemoMembers = [
  {
    userId: "demo-user-me",
    name: "하루",
    intro: "좋아하는 장면과 일상의 온도를 기록해요.",
    avatarUri: "https://i.pravatar.cc/300?img=47",
    owner: true,
    mine: true,
  },
  {
    userId: "demo-user-sora",
    name: "소라",
    intro: "사진과 조용한 일상의 기록을 좋아해요.",
    avatarUri: "https://i.pravatar.cc/300?img=32",
    coHost: true,
  },
  {
    userId: "demo-user-jun",
    name: "준",
    intro: "좋은 음악과 영화를 추천합니다.",
    avatarUri: "https://i.pravatar.cc/300?img=12",
  },
];
